x-airflow-common-env: &airflow-common-env
  AIRFLOW__CORE__EXECUTOR: CeleryExecutor
  AIRFLOW__CORE__FERNET_KEY: ""
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@postgres/airflow"
  AIRFLOW__CELERY__BROKER_URL: "redis://redis:6379/0"
  AIRFLOW__CELERY__RESULT_BACKEND: "db+postgresql://airflow:airflow@postgres/airflow"
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
  AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK:
    "true"
    #AIRFLOW__WEBSERVER__DEFAULT_USER: "admin"

x-airflow-common-volumes: &airflow-common-volumes
  - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
  - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs
  - ${AIRFLOW_PROJ_DIR:-.}/config:/opt/airflow/config
  - ${AIRFLOW_PROJ_DIR:-.}/plugins:/opt/airflow/plugins

services:
  # Airflow Webserver
  airflow-webserver:
    image: apache/airflow:2.10.3
    container_name: airflow-webserver
    ports:
      - "8080:8080"
    depends_on:
      - airflow-init
      - airflow-scheduler
      - airflow-worker
      - kafka1
      - postgres
    environment:
      <<: *airflow-common-env
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
      - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs
      - ${AIRFLOW_PROJ_DIR:-.}/config:/opt/airflow/config
      - ${AIRFLOW_PROJ_DIR:-.}/plugins:/opt/airflow/plugins
    restart: always
    command: webserver
    networks:
      - airflow_network

  # Airflow Scheduler
  airflow-scheduler:
    image: apache/airflow:2.10.3
    container_name: airflow-scheduler
    depends_on:
      - airflow-init
      - kafka1
    environment:
      <<: *airflow-common-env
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
      - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs
      - ${AIRFLOW_PROJ_DIR:-.}/config:/opt/airflow/config
      - ${AIRFLOW_PROJ_DIR:-.}/plugins:/opt/airflow/plugins
    restart: always
    command: scheduler
    networks:
      - airflow_network

  # Airflow Worker
  airflow-worker:
    build: .
    container_name: airflow-worker
    depends_on:
      - airflow-init
      - kafka1
    environment:
      <<: *airflow-common-env
      GOOGLE_CHROME_BIN: "/usr/bin/google-chrome"
      CHROMEDRIVER_PATH: "/usr/local/bin/chromedriver"
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
      MONGOPASS: $MONGOPASS

    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
      - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs
      - ${AIRFLOW_PROJ_DIR:-.}/config:/opt/airflow/config
      - ${AIRFLOW_PROJ_DIR:-.}/plugins:/opt/airflow/plugins
    restart: always
    networks:
      - airflow_network
    command: celery worker
    mem_limit: 8g
    cpus: 4.0

  # Airflow Triggerer
  airflow-triggerer:
    image: apache/airflow:2.10.3
    container_name: airflow-triggerer
    depends_on:
      - airflow-init
      - kafka1
    environment:
      <<: *airflow-common-env
    restart: always
    command: triggerer
    networks:
      - airflow_network

  # Airflow Database Initialization
  airflow-init:
    image: apache/airflow:2.10.3
    container_name: airflow-init
    environment:
      <<: *airflow-common-env
    entrypoint: >
      bash -c "
      airflow db upgrade &&
      airflow users create \
      --username $AIRFLOW_USERNAME \
      --firstname $AIRFLOW_FIRSTNAME \
      --lastname $AIRFLOW_LASTNAME \
      --role Admin \
      --email $AIRFLOW_EMAIL \
      --password $AIRFLOW_PASSWORD"
    restart: "no"
    networks:
      - airflow_network

  # Zookeeper 1
  zookeeper1:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_LISTENER_PORT: 2181
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 10
      ZOOKEEPER_SYNC_LIMIT:
        5
        #volumes:
        #- ./zoo.cfg:/conf/zoo.cfg  # ZooKeeper 설정 파일
        #- ./zk_data:/var/lib/zookeeper/data  # 데이터 디렉토리 마운트
    extra_hosts:
      - "zookeeper2:172.24.0.3"
      - "zookeeper3:172.24.0.4"
    networks:
      - airflow_network

  # Zookeeper 2
  zookeeper2:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper2
    ports:
      - "2182:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_LISTENER_PORT: 2181
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 10
      ZOOKEEPER_SYNC_LIMIT:
        5
        #volumes:
        #- ./zoo.cfg:/conf/zoo.cfg  # ZooKeeper 설정 파일
        #- ./zk_data:/var/lib/zookeeper/data  # 데이터 디렉토리 마운트
    extra_hosts:
      - "zookeeper1:172.24.0.2"
      - "zookeeper3:172.24.0.4"
    networks:
      - airflow_network

  # Zookeeper 3
  zookeeper3:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper3
    ports:
      - "2183:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_LISTENER_PORT: 2181
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 10
      ZOOKEEPER_SYNC_LIMIT:
        5
        #volumes:
        #- ./zoo.cfg:/conf/zoo.cfg  # ZooKeeper 설정 파일
        #- ./zk_data:/var/lib/zookeeper/data  # 데이터 디렉토리 마운트
    extra_hosts:
      - "zookeeper1:172.24.0.2"
      - "zookeeper2:172.24.0.3"
    networks:
      - airflow_network

  # Kafka Broker 1
  kafka1:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1 # 설정 추가
      KAFKA_REPLICA_LAG_TIME_MAX_MS: 10000 # 레플리카가 동기화되지 않은 상태로 허용할 최대 시간 (10초)
      KAFKA_REPLICA_FETCH_MAX_WAIT_MS: 500 # 레플리카가 데이터를 가져오기 전 대기할 최대 시간 (500ms)
    networks:
      - airflow_network
    deploy:
      resources:
        limits:
          memory: "4G"
          cpus: "2"
        reservations:
          memory: "2G"
          cpus: "1"

  # Kafka Broker 2
  kafka2:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka2
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1 # 설정 추가
      KAFKA_REPLICA_LAG_TIME_MAX_MS: 10000 # 레플리카가 동기화되지 않은 상태로 허용할 최대 시간 (10초)
      KAFKA_REPLICA_FETCH_MAX_WAIT_MS: 500 # 레플리카가 데이터를 가져오기 전 대기할 최대 시간 (500ms)
    networks:
      - airflow_network
    deploy:
      resources:
        limits:
          memory: "4G"
          cpus: "2"
        reservations:
          memory: "2G"
          cpus: "1"

  # Kafka Broker 3
  kafka3:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka3
    ports:
      - "9094:9094"
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1 # 설정 추가
      KAFKA_REPLICA_LAG_TIME_MAX_MS: 10000 # 레플리카가 동기화되지 않은 상태로 허용할 최대 시간 (10초)
      KAFKA_REPLICA_FETCH_MAX_WAIT_MS: 500 # 레플리카가 데이터를 가져오기 전 대기할 최대 시간 (500ms)
    networks:
      - airflow_network
    deploy:
      resources:
        limits:
          memory: "4G"
          cpus: "2"
        reservations:
          memory: "2G"
          cpus: "1"

  # Kafka UI
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092,kafka2:9093,kafka3:9094
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper1:2181
    networks:
      - airflow_network

  # Airflow Metadata Database (PostgreSQL)
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - airflow_network

  # Redis (Celery Backend)
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - airflow_network

volumes:
  postgres-data:

networks:
  airflow_network:
    driver: bridge
